change menu according to the device controller
GamesForGood/CandyWrapperDeluxe pull request #15
Opened 2023-06-19 16:21 UTC by NelioQuibe-258

The function added allows the game to change the menu based on the input device controller (Keyboard vs Joystick).
1. When a keyboard is connected, the game will automatically load the "press space to start" menu.
2. When a Joystick is connected, the game will load the "press start to start" menu.

I've attached a short video that shows the new implemented feature.

https://github.com/GamesForGood/CandyWrapperDeluxe/assets/79609481/19e294ac-67a3-4f3f-bf23-ae979bd435ae

2023-06-20 20:12 UTC, Filaipus requested changes

2023-06-20 20:12 UTC, Filaipus commented on Scene/Title.gd
> +		startLabel.visible = false
O que fizeste aqui é um pouco estranho. Porque tens um Sprite1 e um Sprite2? E depois uma startLabel? Não terias somente uma unica imagem e depois mudas as Labels? 

E uma sugestão, neste momento o jogo só reconhece o dispositivo quando inicia. O Godot tem uma função chamada  joy_connection_changed(), onde reconhece quando um dispositivo é ligado. O ideal seria o menu mudar quando o dispositivo é conectado e desconectado. É uma mudança fácil :) 
 https://www.youtube.com/watch?v=Ox1kMM0qcTk

2023-06-20 20:12 UTC, Filaipus commented on export_presets.cfg
Eu não adicionaria as mudanças deste ficheiro. Não tem nada a ver com a tua tarefa, é melhor só mandar para o git um Pull Request com ficheiros pretinentes á tarefa.

2023-06-20 20:12 UTC, Filaipus commented on Script/Game.gd
Eu não adicionaria as mudanças deste ficheiro. Não tem nada a ver com a tua tarefa, é melhor só mandar para o git um Pull Request com ficheiros pretinentes á tarefa.

2023-06-20 20:12 UTC, Filaipus commented on Script/Player.gd
Eu não adicionaria as mudanças deste ficheiro. Não tem nada a ver com a tua tarefa, é melhor só mandar para o git um Pull Request com ficheiros pretinentes á tarefa.

2023-06-20 20:12 UTC, Filaipus commented on project.godot
> +enabled=PoolStringArray(  )
Porque retiraste o plugin?

2023-06-20 22:42 UTC, NelioQuibe-258 commented on Scene/Title.gd
> +		startLabel.visible = false
Entendo. Vou fazer as devidas mundanças

2023-06-20 22:43 UTC, NelioQuibe-258 commented on export_presets.cfg
Certo

2023-06-20 22:44 UTC, NelioQuibe-258 commented on project.godot
> +enabled=PoolStringArray(  )
Nem mexi. So abri

2023-06-20 22:45 UTC, NelioQuibe-258 commented on project.godot
> +enabled=PoolStringArray(  )
Acho que foi removido pelo proprio framework quando abri o projecto na versao 4.0.2 do godot.

2023-06-21 01:31 UTC, Filaipus commented on project.godot
> +enabled=PoolStringArray(  )
Ok. Também sou meio novo com o Godot, não sei como funciona haha. Eu sugeria não fazer commit desta mudança :)

2023-06-21 23:30 UTC, closed without merging